Iter21 app configuration with file
jbakhtin/rtagent pull request #28
Opened 2023-09-23 19:15 UTC by jbakhtin

2023-10-01 13:01 UTC, arttet requested changes

2023-10-01 13:01 UTC, arttet commented on pem/client.csr
> +-----BEGIN CERTIFICATE REQUEST-----
It shouldn't be in the `commits`

2023-10-03 07:10 UTC, jbakhtin commented on internal/agent/aggregator/config.go
> +type Config interface {
I wanted to abstract from the specific implementation of the config pkg. In the future, it was possible to embed another config, the main thing is that the necessary getters would be implemented in the new config. 

O and D principles from SOLID

2023-10-03 11:52 UTC, jbakhtin commented on pem/client.csr
> +-----BEGIN CERTIFICATE REQUEST-----
removed

2023-10-03 12:02 UTC, merged